
#ifndef __MTN_WB_INTERFACE__
#define __MTN_WB_INTERFACE__

#define X_MOTOR_SPEED_PROFILE_NUM  4
#define Y_MOTOR_SPEED_PROFILE_NUM  4
#define Z_MOTOR_SPEED_PROFILE_NUM  6

#define X_MOTOR_CONTROL_PROFILE_NUM  12
#define Y_MOTOR_CONTROL_PROFILE_NUM  12
#define Z_MOTOR_CONTROL_PROFILE_NUM  9

typedef struct SERVO_SPEED_PROFILE
{
    short nMaxVel;
    short nMaxAcc;
    long  lJerk;
} _SERVO_SPEED_PROFILE;

typedef struct SERVO_MOTION_PARAMETER
{
    SERVO_SPEED_PROFILE stSpeedProfileX[X_MOTOR_SPEED_PROFILE_NUM];
    SERVO_SPEED_PROFILE stSpeedProfileY[Y_MOTOR_SPEED_PROFILE_NUM];
    SERVO_SPEED_PROFILE stSpeedProfileZ[Z_MOTOR_SPEED_PROFILE_NUM];
} _SERVO_MOTION_PARAMETER;

typedef struct SERVO_CONTROL_PROFILE
{
    long lVelGain;
    long lVelIntegrator;
    long lPosGain;
    long lAccFeedFwd;
} _SERVO_CONTROL_PROFILE;


typedef struct SERVO_CONTROL_PARAMETER
{
    SERVO_CONTROL_PROFILE stControlProfileX[X_MOTOR_CONTROL_PROFILE_NUM];
    SERVO_CONTROL_PROFILE stControlProfileY[Y_MOTOR_CONTROL_PROFILE_NUM];
    SERVO_CONTROL_PROFILE stControlProfileZ[Z_MOTOR_CONTROL_PROFILE_NUM];
} _SERVO_CONTROL_PARAMETER;

#endif // __MTN_WB_INTERFACE__